# Generated by Django 6.1.1 on 2026-09-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='banner',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='logo',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
    ]
