# Generated by Django 6.1.1 on 2026-09-23 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_image_path_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProposal',
            fields=[
            ],
            options={
                'verbose_name': 'proposed card',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.card',),
        ),
        migrations.AddField(
            model_name='card',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='banner',
            field=models.FileField(blank=True, max_length=255, upload_to='proposals/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='komi_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='logo',
            field=models.FileField(blank=True, max_length=255, upload_to='proposals/'),
        ),
    ]
